name: Build and Upload to Registry

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.gitlab.com
          repository: bradenr/switchboard-ui
          tags: latest

      - name: Set up kubectl
        uses: matootie/dokube@v1.3.2
        with:
          personalAccessToken: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
            clusterName: mykube

      - name: Rollout Kubernetes deployment
        run: kubectl rollout restart deployment/switchboard-ui
